### ISSUE TITLE
Enhancement: Opening drawer

### ISSUE THREAD

**Issue by spitzform** [SCCapstone/FitLivin#70]
It feels somewhat unnatural to have to click on the little bodybuilder icon to open the nav drawer.  I would've thought clicking on the title of the page (e.g. 'Profile', 'Nutrition', etc) would open/close the drawer being that it is in the top left corner where a menu button usually is.

**Comment by pkchoksi** [comment]
Again, we would consider it on future versions. Please let us know if there are any bugs.

**Comment by sandifee** [comment]
The quality assurance milestone was supposed to be last week..Not the day before the due date.

**Comment by sandifee** [comment]
And this was Vidal's recommendation
